//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customerr
    {
        public int customerID { get; set; }
        public string customerNameSurname { get; set; }
        public string customerPhone { get; set; }
        public Nullable<int> customerAge { get; set; }
        public Nullable<int> customerBalance { get; set; }
        public Nullable<int> customerDownPayment { get; set; }
        public Nullable<int> branchID { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
